In [ ]:
#This is pyenv file for analyze data after making subset and AI classification

In [14]:
import pandas as pd
pd.set_option('display.max_columns', 50)

In [24]:
df_2025 = pd.read_csv('Recall_classified2025.csv')
df_2024 = pd.read_csv('Recall_classified2024.csv')
df_2005 = pd.read_csv('Recall_classified2005.csv')
df_2010 = pd.read_csv('Recall_classified2010.csv')
df_2015 = pd.read_csv('Recall_classified2015.csv')

In [96]:
df_2000 = pd.read_csv('Recall_classified2000.csv')

In [103]:
df_2020 = pd.read_csv('Recall_classified2020.csv')

In [116]:
df_2026 = pd.read_csv('Recall_classified2026.csv')

In [104]:
df_2020.head(10)

,Unnamed: 0,RECORD_ID,CAMPNO,MAKETXT,MODELTXT,YEARTXT,MFGCAMPNO,COMPNAME,MFGNAME,BGMAN,ENDMAN,RCLTYPECD,POTAFF,ODATE,INFLUENCED_BY,MFGTXT,RCDATE,DATEA,RPNO,FMVSS,DESC_DEFECT,CONEQUENCE_DEFECT,CORRECTIVE_ACTION,NOTES,RCL_CMPT_ID,MFR_COMP_NAME,MFR_COMP_DESC,MFR_COMP_PTNO,PARK_IT,PARK_OUTSIDE,ai_guess
0,0,134691,18V902000,IC BUS,CESB,2020,18520,"SERVICE BRAKES, HYDRAULIC:BRAKE FLUID LOW WARN...","Navistar, Inc.",20171204.0,20180329.0,V,475,20190130.0,MFR,"International Motors, LLC",20181219,20190130,NaN,NaN,"Navistar, Inc. (Navistar) is recalling certain...",A false code or a brake warning light may lead...,"Navistar has notified owners, and dealers will...",Owners may also contact the National Highway T...,96788003798717000000065,NaN,NaN,NaN,No,No,electronics
1,1,135829,18V884000,BLUE BIRD,VISION SCHOOL BUS,2020,R19ZV-SB,POWER TRAIN:AUTOMATIC TRANSMISSION:LEVER AND L...,Blue Bird Body Company,20120124.0,20180927.0,V,5169,20190207.0,MFR,Blue Bird Body Company,20181212,20181217,NaN,NaN,Blue Bird Body Company (Blue Bird) is recallin...,A hydraulic brake fluid leak or a fuel line fa...,"Blue Bird will notify owners, and dealers will...",Owners may also contact the National Highway T...,96447003616717000000183,NaN,NaN,NaN,No,No,chasies
2,2,135831,18V884000,BLUE BIRD,VISION SCHOOL BUS,2020,R19ZV-SB,"SERVICE BRAKES, HYDRAULIC",Blue Bird Body Company,20120124.0,20180927.0,V,5169,20190207.0,MFR,Blue Bird Body Company,20181212,20181217,NaN,NaN,Blue Bird Body Company (Blue Bird) is recallin...,A hydraulic brake fluid leak or a fuel line fa...,"Blue Bird will notify owners, and dealers will...",Owners may also contact the National Highway T...,96447003616717000000062,NaN,NaN,NaN,No,No,chasies
3,3,136428,18V846000,BLUE BIRD,ALL AMERICAN SCHOOL BUS,2020,R18ZT-SB,SEATS,Blue Bird Body Company,20180924.0,20180924.0,V,12,20181212.0,MFR,Blue Bird Body Company,20181128,20181203,NaN,NaN,Blue Bird Body Company (Blue Bird) is recallin...,"In the event of a crash, if the bus seat detac...","Blue Bird will notify owners, and dealers will...",Owners may also contact the National Highway T...,95666003826717000000318,NaN,NaN,NaN,No,No,safety_equipment
4,4,136430,18V846000,BLUE BIRD,VISION SCHOOL BUS,2020,R18ZT-SB,SEATS,Blue Bird Body Company,20180724.0,20181023.0,V,12,20181212.0,MFR,Blue Bird Body Company,20181128,20181203,NaN,NaN,Blue Bird Body Company (Blue Bird) is recallin...,"In the event of a crash, if the bus seat detac...","Blue Bird will notify owners, and dealers will...",Owners may also contact the National Highway T...,95666003616717000000318,NaN,NaN,NaN,No,No,safety_equipment
5,5,136697,18V566000,BLUE BIRD,VISION SCHOOL BUS,2020,R18ZN-SB,EQUIPMENT:OTHER:LABELS,Blue Bird Body Company,20171031.0,20180827.0,V,551,20180926.0,MFR,Blue Bird Body Company,20180828,20180831,NaN,213.0,Blue Bird Body Company (Blue Bird) is recallin...,"Without a warning label, the seat may be used ...","Blue Bird will notify owners, and dealers will...",Owners may also contact the National Highway T...,90266003616717000000349,NaN,NaN,NaN,No,No,safety_equipment
6,6,136698,18V566000,BLUE BIRD,VISION SCHOOL BUS,2020,R18ZN-SB,SEATS,Blue Bird Body Company,20171031.0,20180827.0,V,551,20180926.0,MFR,Blue Bird Body Company,20180828,20180831,NaN,213.0,Blue Bird Body Company (Blue Bird) is recallin...,"Without a warning label, the seat may be used ...","Blue Bird will notify owners, and dealers will...",Owners may also contact the National Highway T...,90266003616717000000318,NaN,NaN,NaN,No,No,safety_equipment
7,7,138121,18V821000,IC BUS,CESB,2020,18517,"SERVICE BRAKES, AIR","Navistar, Inc.",20180125.0,20181010.0,V,187,20181220.0,MFR,"International Motors, LLC",20181120,20181127,NaN,NaN,"Navistar, Inc. (Navistar) is recalling certain...",A vehicle pulling to the right during braking ...,"Navistar will notify owners, and dealers will ...",Owners may also contact the National Highway T...,95126003798717000000087,NaN,NaN,NaN,No,No,chasies
8,8,138201,18V885000,BLUE BIRD,VISION TRANSIT BUS,2020,R19ZV-NSB,POWER TRAIN:AUTOMATIC TRANSMISSION:LEVER AND L...,Blue Bird Body Company,20140924.0,20180918.0,V,32,20190207.0,MFR,Blue Bird Body Company,20181212,20181217,NaN,NaN,Blue Bird Body Company (Blue Bird) is recallin...,A hydraulic brake fluid leak or a fuel line fa...,"Blue Bird will notify owners, and dealers will...",Owners may also contact the National Highway T...,96466003854717000000183,NaN,NaN,NaN,No,No,others
9,9,138202,18V885000,BLUE BIRD,VISION TRANSIT BUS,2020,R19ZV-NSB,"SERVICE BRAKES, HYDRAULIC",Blue Bird Body Company,20140924.0,20180918.0,V,32,20190207.0,MFR,Blue Bird Body Company,20181212,20181217,NaN,NaN,Blue Bird Body Company (Blue Bird) is recallin...,A hydraulic brake fluid leak or a fuel line fa...,"Blue Bird will notify owners, and dealers will...",Owners may also contact the National Highway T...,96466003854717000000062,NaN,NaN,NaN,No,No,others

In [30]:
df_2025.value_counts('ai_guess')

ai_guess
software            4620
electronics         1698
others              1280
chasies             1105
safety_equipment     546
powertrain           368
Name: count, dtype: int64

In [26]:
df_2005.value_counts('ai_guess')

ai_guess
others              1694
safety_equipment    1074
chasies              766
electronics          652
powertrain           421
software              66
Name: count, dtype: int64

In [27]:
df_2010.value_counts('ai_guess')

ai_guess
safety_equipment    2009
others              1926
electronics         1098
chasies              687
powertrain           607
software             260
Name: count, dtype: int64

In [28]:
df_2015.value_counts('ai_guess')

ai_guess
others              2212
safety_equipment    1437
electronics         1196
chasies             1193
powertrain           908
software             445
Name: count, dtype: int64

In [56]:
df_2025.value_counts('MFGNAME').head(20)

MFGNAME
Toyota Motor Engineering & Manufacturing    3804
PACCAR Incorporated                          741
Ford Motor Company                           582
Mercedes-Benz USA, LLC                       447
Daimler Trucks North America, LLC            433
Honda (American Honda Motor Co.)             270
New Flyer of America, Inc.                   225
Hyundai Motor America                        221
Forest River, Inc.                           186
Nissan North America, Inc.                   182
BMW of North America, LLC                    131
Chrysler (FCA US, LLC)                       126
GEM WAEV LLC                                 108
Kia America, Inc.                            104
Volkswagen Group of America, Inc.             93
International Motors, LLC                     89
Keystone RV Company                           86
Prevost Car (US) Inc.                         84
Altec Industries, Inc.                        76
Autocar, LLC                                  74
Name: count, dtype: int64

In [12]:
df_2025.shape

(9617, 31)

In [193]:
df_2025[(df_2025['MFGNAME']=="Toyota Motor Engineering & Manufacturing")&(df_2025['ai_guess']=="software")].head(30)

,Unnamed: 0,RECORD_ID,CAMPNO,MAKETXT,MODELTXT,YEARTXT,MFGCAMPNO,COMPNAME,MFGNAME,BGMAN,ENDMAN,RCLTYPECD,POTAFF,ODATE,INFLUENCED_BY,MFGTXT,RCDATE,DATEA,RPNO,FMVSS,DESC_DEFECT,CONEQUENCE_DEFECT,CORRECTIVE_ACTION,NOTES,RCL_CMPT_ID,MFR_COMP_NAME,MFR_COMP_DESC,MFR_COMP_PTNO,PARK_IT,PARK_OUTSIDE,ai_guess
607,607,268905,24V708000,TOYOTA,COROLLA HYBRID,2025,24TA11,"SERVICE BRAKES, HYDRAULIC:POWER ASSIST:ELECTRI...",Toyota Motor Engineering & Manufacturing,NaN,NaN,V,145383,20241119.0,MFR,Toyota Motor Corporation,20240920,20240924,NaN,NaN,Toyota Motor Engineering & Manufacturing (Toyo...,A loss of power brake assist can extend the di...,Dealers will update the skid control ECU softw...,Owners may also contact the National Highway T...,127478005636673000001666,"Actuator Assy, Brake with Fluid",Brake Actuator Assembly,44050-12J32,No,No,software
608,608,268906,24V708000,TOYOTA,COROLLA HYBRID,2025,24TA11,"SERVICE BRAKES, HYDRAULIC:POWER ASSIST:ELECTRI...",Toyota Motor Engineering & Manufacturing,NaN,NaN,V,145383,20241119.0,MFR,Toyota Motor Corporation,20240920,20240924,NaN,NaN,Toyota Motor Engineering & Manufacturing (Toyo...,A loss of power brake assist can extend the di...,Dealers will update the skid control ECU softw...,Owners may also contact the National Highway T...,127478005636673000001666,"Actuator Assy, Brake with Fluid",Brake Actuator Assembly,44050-12J31,No,No,software
609,609,268907,24V708000,TOYOTA,COROLLA HYBRID,2025,24TA11,"SERVICE BRAKES, HYDRAULIC:POWER ASSIST:ELECTRI...",Toyota Motor Engineering & Manufacturing,NaN,NaN,V,145383,20241119.0,MFR,Toyota Motor Corporation,20240920,20240924,NaN,NaN,Toyota Motor Engineering & Manufacturing (Toyo...,A loss of power brake assist can extend the di...,Dealers will update the skid control ECU softw...,Owners may also contact the National Highway T...,127478005636673000001666,"Actuator Assy, Brake with Fluid",Brake Actuator Assembly,44050-12J30,No,No,software
610,610,268908,24V708000,TOYOTA,COROLLA HYBRID,2025,24TA11,"SERVICE BRAKES, HYDRAULIC:POWER ASSIST:ELECTRI...",Toyota Motor Engineering & Manufacturing,NaN,NaN,V,145383,20241119.0,MFR,Toyota Motor Corporation,20240920,20240924,NaN,NaN,Toyota Motor Engineering & Manufacturing (Toyo...,A loss of power brake assist can extend the di...,Dealers will update the skid control ECU softw...,Owners may also contact the National Highway T...,127478005636673000001666,"Actuator Assy, Brake with Fluid",Brake Actuator Assembly,44050-0A201,No,No,software
611,611,268909,24V708000,TOYOTA,COROLLA HYBRID,2025,24TA11,"SERVICE BRAKES, HYDRAULIC:POWER ASSIST:ELECTRI...",Toyota Motor Engineering & Manufacturing,NaN,NaN,V,145383,20241119.0,MFR,Toyota Motor Corporation,20240920,20240924,NaN,NaN,Toyota Motor Engineering & Manufacturing (Toyo...,A loss of power brake assist can extend the di...,Dealers will update the skid control ECU softw...,Owners may also contact the National Highway T...,127478005636673000001666,"Actuator Assy, Brake with Fluid",Brake Actuator Assembly,44050-0A200,No,No,software
612,612,268910,24V708000,TOYOTA,COROLLA HYBRID,2025,24TA11,"SERVICE BRAKES, ELECTRIC:SOFTWARE/PROGRAMMING",Toyota Motor Engineering & Manufacturing,NaN,NaN,V,145383,20241119.0,MFR,Toyota Motor Corporation,20240920,20240924,NaN,NaN,Toyota Motor Engineering & Manufacturing (Toyo...,A loss of power brake assist can extend the di...,Dealers will update the skid control ECU softw...,Owners may also contact the National Highway T...,127478005636673000001661,"Actuator Assy, Brake with Fluid",Brake Actuator Assembly,44050-12J32,No,No,software
613,613,268911,24V708000,TOYOTA,COROLLA HYBRID,2025,24TA11,"SERVICE BRAKES, ELECTRIC:SOFTWARE/PROGRAMMING",Toyota Motor Engineering & Manufacturing,NaN,NaN,V,145383,20241119.0,MFR,Toyota Motor Corporation,20240920,20240924,NaN,NaN,Toyota Motor Engineering & Manufacturing (Toyo...,A loss of power brake assist can extend the di...,Dealers will update the skid control ECU softw...,Owners may also contact the National Highway T...,127478005636673000001661,"Actuator Assy, Brake with Fluid",Brake Actuator Assembly,44050-12J31,No,No,software
614,614,268912,24V708000,TOYOTA,COROLLA HYBRID,2025,24TA11,"SERVICE BRAKES, ELECTRIC:SOFTWARE/PROGRAMMING",Toyota Motor Engineering & Manufacturing,NaN,NaN,V,145383,20241119.0,MFR,Toyota Motor Corporation,20240920,20240924,NaN,NaN,Toyota Motor Engineering & Manufacturing (Toyo...,A loss of power brake assist can extend the di...,Dealers will update the skid control ECU softw...,Owners may also contact the National Highway T...,127478005636673000001661,"Actuator Assy, Brake with Fluid",Brake Actuator Assembly,44050-12J30,No,No,software
615,615,268913,24V708000,TOYOTA,COROLLA HYBRID,2025,24TA11,"SERVICE BRAKES, ELECTRIC:SOFTWARE/PROGRAMMING",Toyota Motor Engineering & Manufacturing,NaN,NaN,V,145383,20241119.0,MFR,Toyota Motor Corporation,20240920,20240924,NaN,NaN,Toyota Motor Engineering & Manufacturing (Toyo...,A loss of power brake assist can extend the di...,Dealers will update the skid control ECU softw...,Owners may also contact the National Highway T...,127478005636673000001661,"Actuator Assy, Brake with Fluid",Brake Actuator Assembly,44050-0A201,No,No,software
616,616,268914,24V708000,TOYOTA,COROLLA HYBRID,2025,24TA11,"SERVICE BRAKES, ELECTRIC:SOFTWARE/PROGRAMMING",Toyota Motor Engineering & Manufacturing,NaN,NaN,V,145383,20241119.0,MFR,Toyota Motor Corporation,20240920,20240924,NaN,NaN,Toyota Motor Engineering & Manufacturing (Toyo...,A loss of power brake assist can extend the di...,Dealers will update the skid control ECU softw...,Owners may also contact the National Highway T...,127478005636673000001661,"Actuator Assy, Brake with Fluid",Brake Actuator Assembly,44050-0A200,No,No,software
1854,1854,291802,25V577000,LEXUS,RZ,2025,"25TB07,25LB04,WRD25",VISIBILITY:DEFROSTER/DEFOGGER/HVAC SYSTEM,Toyota Motor Engineering & Manufacturing,20230123.0,20250612.0,V,94320,20251017.0,MFR,Toyota Motor Corporation,20250904,20250905,NaN,NaN,Toyota Motor Engineering & Manufacturing (Toyo...,An inoperative defroster and defogger system c...,Dealers will update the HVAC control ECU softw...,NaN,260491005636655000000251,"Amplifier Assy, Air Conditioner",HVAC Control ECU,886H0-46010,No,No,software
1859,1859,291807,25V577000,LEXUS,RZ,2025,"25TB07,25LB04,WRD25",VISIBILITY:DEFROSTER/DEFOGGER/HVAC SYSTEM,Toyota Motor Engineering & Manufacturing,20230123.0,20250612.0,V,94320,20251017.0,MFR,Toyota Motor Corporation,20250904,20250905,NaN,NaN,Toyota Motor Engineering & Manufacturing (Toyo...,An inoperative defroster and defogger system c...,Dealers will update the HVAC control ECU softw...,NaN,260491005636655000000251,"Amplifier Assy, Air Conditioner",HVAC Control ECU,88650-42A00,No,No,software
1862,1862,291838,25V577000,TOYOTA,BZ4X,2025,"25TB07,25LB04,WRD25",VISIBILITY:DEFROSTER/DEFOGGER/HVAC SYSTEM,Toyota Motor Engineering & Manufacturing,20250330.0,20250612.0,V,94320,20251017.0,MFR,Toyota Motor Corporation,20250904,20250905,NaN,NaN,Toyota Motor Engineering & Manufacturing (Toyo...,An inoperative defroster and defogger system c...,Dealers will update the HVAC control ECU softw...,NaN,260491005636667000000251,"Amplifier Assy, Air Conditioner",HVAC Control ECU,886H0-46070,No,No,software
1865,1865,291841,25V577000,TOYOTA,BZ4X,2025,"25TB07,25LB04,WRD25",VISIBILITY:DEFROSTER/DEFOGGER/HVAC SYSTEM,Toyota Motor Engineering & Manufacturing,20250330.0,20250612.0,V,94320,20251017.0,MFR,Toyota Motor Corporation,20250904,20250905,NaN,NaN,Toyota Motor Engineering & Manufacturing (Toyo...,An inoperative defroster and defogger system c...,Dealers will update the HVAC control ECU softw...,NaN,260491005636667000000251,"Amplifier Assy, Air Conditioner",HVAC Control ECU,886H0-46021,No,No,software
1867,1867,291843,25V577000,TOYOTA,BZ4X,2025,"25TB07,25LB04,WRD25",VISIBILITY:DEFROSTER/DEFOGGER/HVAC SYSTEM,Toyota Motor Engineering & Manufacturing,20250330.0,20250612.0,V,94320,20251017.0,MFR,Toyota Motor Corporation,20250904,20250905,NaN,NaN,Toyota Motor Engineering & Manufacturing (Toyo...,An inoperative defroster and defogger system c...,Dealers will update the HVAC control ECU softw...,NaN,260491005636667000000251,"Amplifier Assy, Air Conditioner",HVAC Control ECU,886H0-46011,No,No,software
1868,1868,291844,25V577000,TOYOTA,BZ4X,2025,"25TB07,25LB04,WRD25",VISIBILITY:DEFROSTER/DEFOGGER/HVAC SYSTEM,Toyota Motor Engineering & Manufacturing,20250330.0,20250612.0,V,94320,20251017.0,MFR,Toyota Motor Corporation,20250904,20250905,NaN,NaN,Toyota Motor Engineering & Manufacturing (Toyo...,An inoperative defroster and defogger system c...,Dealers will update the HVAC control ECU softw...,NaN,260491005636667000000251,"Amplifier Assy, Air Conditioner",HVAC Control ECU,886H0-46010,No,No,software
2109,2109,293385,25V744000,TOYOTA,PRIUS,2025,25TB13/25LB06/WRE25,BACK OVER PREVENTION:DISPLAY FUNCTION,Toyota Motor Engineering & Manufacturing,20221012.0,20250701.0,V,1024407,20251205.0,MFR,Toyota Motor Corporation,20251030,20251030,NaN,111.0,Toyota Motor Engineering & Manufacturing (Toyo...,A rearview camera that fails to display an ima...,Dealers will update the parking assist softwar...,NaN,260709005636690000001883,"Computer, Parking Assist",Parking Assist ECU,86792-33180,No,No,software
2110,2110,293386,25V744000,TOYOTA,PRIUS,2025,25TB13/25LB06/WRE25,BACK OVER PREVENTION:DISPLAY FUNCTION,Toyota Motor Engineering & Manufacturing,20221012.0,20250701.0,V,1024407,20251205.0,MFR,Toyota Motor Corporation,20251030,20251030,NaN,111.0,Toyota Motor Engineering & Manufacturing (Toyo...,A rearview camera that fails to display an ima...,Dealers will update the parking assist softwar...,NaN,260709005636690000001883,"Computer, Parking Assist",Parking Assist ECU,86792-30690,No,No,software
2111,2111,293387,25V744000,TOYOTA,PRIUS,2025,25TB13/25LB06/WRE25,BACK OVER PREVENTION:DISPLAY FUNCTION,Toyota Motor Engineering & Manufacturing,20221012.0,20250701.0,V,1024407,20251205.0,MFR,Toyota Motor Corporation,20251030,20251030,NaN,111.0,Toyota Motor Engineering & Manufacturing (Toyo...,A rearview camera that fails to display an ima...,Dealers will update the parking assist softwar...,NaN,260709005636690000001883,"Computer, Parking Assist",Parking Assist ECU,86792-30600,No,No,software
2112,2112,293388,25V744000,TOYOTA,PRIUS,2025,25TB13/25LB06/WRE25,BACK OVER PREVENTION:DISPLAY FUNCTION,Toyota Motor Engineering & Manufacturing,20221012.0,20250701.0,V,1024407,20251205.0,MFR,Toyota Motor Corporation,20251030,20251030,NaN,111.0,Toyota Motor Engineering & Manufacturing (Toyo...,A rearview camera that fails to display an ima...,Dealers will update the parking assist softwar...,NaN,260709005636690000001883,"Computer, Parking Assist",Parking Assist ECU,86792-30520,No,No,software
2113,2113,293389,25V744000,TOYOTA,PRIUS,2025,25TB13/25LB06/WRE25,BACK OVER PREVENTION:DISPLAY FUNCTION,Toyota Motor Engineering & Manufacturing,20221012.0,20250701.0,V,1024407,20251205.0,MFR,Toyota Motor Corporation,20251030,20251030,NaN,111.0,Toyota Motor Engineering & Manufacturing (Toyo...,A rearview camera that fails to display an ima...,Dealers will update the parking assist softwar...,NaN,260709005636690000001883,"Computer, Parking Assist",Parking Assist ECU,86792-11020,No,No,software
2114,2114,293600,25V744000,TOYOTA,RAV4 HYBRID,2025,25TB13/25LB06/WRE25,BACK OVER PREVENTION:DISPLAY FUNCTION,Toyota Motor Engineering & Manufacturing,20220620.0,20251009.0,V,1024407,20251205.0,MFR,Toyota Motor Corporation,20251030,20251030,NaN,111.0,Toyota Motor Engineering & Manufacturing (Toyo...,A rearview camera that fails to display an ima...,Dealers will update the parking assist softwar...,NaN,260709005636693000001883,"Computer, Parking Assist",Parking Assist ECU,86792-78430,No,No,software
2115,2115,293601,25V744000,TOYOTA,RAV4 HYBRID,2025,25TB13/25LB06/WRE25,BACK OVER PREVENTION:DISPLAY FUNCTION,Toyota Motor Engineering & Manufacturing,20220620.0,20251009.0,V,1024407,20251205.0,MFR,Toyota Motor Corporation,20251030,20251030,NaN,111.0,Toyota Motor Engineering & Manufacturing (Toyo...,A rearview camera that fails to display an ima...,Dealers will update the parking assist softwar...,NaN,260709005636693000001883,"Computer, Parking Assist",Parking Assist ECU,86792-78360,No,No,software
2116,2116,293602,25V744000,TOYOTA,RAV4 HYBRID,2025,25TB13/25LB06/WRE25,BACK OVER PREVENTION:DISPLAY FUNCTION,Toyota Motor Engineering & Manufacturing,20220620.0,20251009.0,V,1024407,20251205.0,MFR,Toyota Motor Corporation,20251030,20251030,NaN,111.0,Toyota Motor Engineering & Manufacturing (Toyo...,A rearview camera that fails to display an ima...,Dealers will update the parking assist softwar...,NaN,260709005636693000001883,"Computer, Parking Assist",Parking Assist ECU,86792-78321,No,No,software
2117,2117,293603,25V744000,TOYOTA,RAV4 HYBRID,2025,25TB13/25LB06/WRE25,BACK OVER PREVENTION:DISPLAY FUNCTION,Toyota Motor Engineering & Manufacturing,20220620.0,20251009.0,V,1024407,20251205.0,MFR,Toyota Motor Corporation,20251030,20251030,NaN,111.0,Toyota Motor Engineering & Manufacturing (Toyo...,A rearview camera that fails to display an ima...,Dealers will update the parking assist softwar...,NaN,260709005636693000001883,"Computer, Parking Assist",Parking Assist ECU,86792-78320,No,No,software
2118,2118,293604,25V744000,TOYOTA,RAV4 HYBRID,2025,25TB13/25LB06/WRE25,BACK OVER PREVENTION:DISPLAY FUNCTION,Toyota Motor Engineering & Manufacturing,20220620.0,20251009.0,V,1024407,20251205.0,MFR,Toyota Motor Corporation,20251030,20251030,NaN,111.0,Toyota Motor Engineering & Manufacturing (Toyo...,A rearview camera that fails to display an ima...,Dealers will update the parking assist softwar...,NaN,260709005636693000001883,"Computer, Parking Assist",Parking Assist ECU,86792-78241,No,No,software
2119,2119,293605,25V744000,TOYOTA,RAV4 HYBRID,2025,25TB13/25LB06/WRE25,BACK OVER PREVENTION:DISPLAY FUNCTION,Toyota Motor Engineering & Manufacturing,20220620.0,20251009.0,V,1024407,20251205.0,MFR,Toyota Motor Corporation,20251030,20251030,NaN,111.0,Toyota Motor Engineering & Manufacturing (Toyo...,A rearview camera that fails to display an ima...,Dealers will update the parking assist softwar...,NaN,260709005636693000001883,"Computer, Parking Assist",Parking Assist ECU,86792-78240,No,No,software
2120,2120,293606,25V744000,TOYOTA,RAV4 HYBRID,2025,25TB13/25LB06/WRE25,BACK OVER PREVENTION:DISPLAY FUNCTION,Toyota Motor Engineering & Manufacturing,20220620.0,20251009.0,V,1024407,20251205.0,MFR,Toyota Motor Corporation,20251030,20251030,NaN,111.0,Toyota Motor Engineering & Manufacturing (Toyo...,A rearview camera that fails to display an ima...,Dealers will update the parking assist softwar...,NaN,260709005636693000001883,"Computer, Parking Assist",Parking Assist ECU,86792-62180,No,No,software
2121,2121,293607,25V744000,TOYOTA,RAV4 HYBRID,2025,25TB13/25LB06/WRE25,BACK OVER PREVENTION:DISPLAY FUNCTION,Toyota Motor Engineering & Manufacturing,20220620.0,20251009.0,V,1024407,20251205.0,MFR,Toyota Motor Corporation,20251030,20251030,NaN,111.0,Toyota Motor Engineering & Manufacturing (Toyo...,A rearview camera that fails to display an ima...,Dealers will update the parking assist softwar...,NaN,260709005636693000001883,"Computer, Parking Assist",Parking Assist ECU,86792-62140,No,No,software
2122,2122,293608,25V744000,TOYOTA,RAV4 HYBRID,2025,25TB13/25LB06/WRE25,BACK OVER PREVENTION:DISPLAY FUNCTION,Toyota Motor Engineering & Manufacturing,20220620.0,20251009.0,V,1024407,20251205.0,MFR,Toyota Motor Corporation,20251030,20251030,NaN,111.0,Toyota Motor Engineering & Manufacturing (Toyo...,A rearview camera that fails to display an ima...,Dealers will update the parking assist softwar...,NaN,260709005636693000001883,"Computer, Parking Assist",Parking Assist ECU,86792-62120,No,No,software

In [22]:
df_2025.value_counts('COMPNAME').head(10)

COMPNAME
BACK OVER PREVENTION:DISPLAY FUNCTION                                                                               2460
ELECTRICAL SYSTEM: INSTRUMENT CLUSTER/PANEL                                                                         1365
ELECTRICAL SYSTEM:SOFTWARE                                                                                           300
SERVICE BRAKES, HYDRAULIC:ANTILOCK/TRACTION CONTROL/ELECTRONIC LIMITED SLIP:CONTROL UNIT/MODULE                      233
BACK OVER PREVENTION:SOFTWARE                                                                                        212
STEERING:LINKAGES:TIE ROD ASSEMBLY                                                                                   185
STEERING                                                                                                             157
ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION BATTERY:MANAGEMENT SYSTEM/ENERGY CONTROL MODULE (BMS/BECM):SOFTWARE     156
ELECTRICAL SYSTEM:WIRING                                                                                             137
EQUIPMENT:OTHER:LABELS                                                                                               104
Name: count, dtype: int64

In [31]:
df_2025_ai=df_2025.value_counts('ai_guess')

In [39]:
df_2025_ai=df_2025_ai.reset_index()

In [40]:
df_2025_ai.to_csv('2025_ai.csv',index=False)

In [42]:
df_2025[df_2025['ai_guess']=="software"].value_counts('COMPNAME').head(30)

COMPNAME
BACK OVER PREVENTION:DISPLAY FUNCTION                                                                               2453
ELECTRICAL SYSTEM: INSTRUMENT CLUSTER/PANEL                                                                         1252
ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION BATTERY:MANAGEMENT SYSTEM/ENERGY CONTROL MODULE (BMS/BECM):SOFTWARE     156
BACK OVER PREVENTION:SOFTWARE                                                                                        120
BACK OVER PREVENTION:WARNINGS:EXTERNAL/PEDESTRIAN ALERT                                                               85
ELECTRICAL SYSTEM:SOFTWARE                                                                                            53
FORWARD COLLISION AVOIDANCE: AUTOMATIC EMERGENCY BRAKING                                                              50
ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION BATTERY                                                                  43
FUEL SYSTEM, GASOLINE:FUEL INJECTION SYSTEM                                                                           42
EXTERIOR LIGHTING:BRAKE LIGHTS                                                                                        36
ELECTRICAL SYSTEM:PROPULSION SYSTEM                                                                                   31
ENGINE AND ENGINE COOLING:ENGINE:ENGINE CONTROL MODULE (ECU/ECM):SOFTWARE                                             28
BACK OVER PREVENTION: SENSING SYSTEM: CAMERA                                                                          27
EQUIPMENT:APPLIANCE:TV/RADIO/SPEAKERS                                                                                 24
EXTERIOR LIGHTING:LIGHTING CONTROL MODULE:SOFTWARE                                                                    21
EXTERIOR LIGHTING:HEADLIGHTS                                                                                          14
FORWARD COLLISION AVOIDANCE: WARNINGS:EXTERNAL/PEDESTRIAN ALERT                                                       12
ELECTRICAL SYSTEM:ADAS                                                                                                12
ELECTRICAL SYSTEM:BODY CONTROL MODULE:SOFTWARE                                                                         9
EXTERIOR LIGHTING:TAIL LIGHTS                                                                                          9
SERVICE BRAKES, HYDRAULIC:POWER ASSIST:ELECTRIC:CONTROL MODULE:SOFTWARE                                                8
ELECTRONIC STABILITY CONTROL (ESC)                                                                                     7
AIR BAGS: AIR BAG/RESTRAINT CONTROL MODULE:SOFTWARE                                                                    7
COMMUNICATION: AUTO CRASH NOTIFICATION                                                                                 7
ELECTRICAL SYSTEM:PROPULSION SYSTEM:INVERTER                                                                           6
EQUIPMENT:ELECTRICAL:INFOTAINMENT:SOFTWARE                                                                             6
BACK OVER PREVENTION                                                                                                   6
VISIBILITY:DEFROSTER/DEFOGGER/HVAC SYSTEM                                                                              6
VEHICLE SPEED CONTROL:THROTTLE:THROTTLE POSITION SENSOR (TPS)                                                          6
SERVICE BRAKES, HYDRAULIC:POWER ASSIST:ELECTRIC:SOLENOID/ACTUATOR                                                      5
Name: count, dtype: int64

In [51]:
df_2015[(df_2015['PARK_IT']=="Yes")].value_counts('ai_guess')

ai_guess
chasies             21
powertrain          10
others               6
safety_equipment     4
electronics          2
Name: count, dtype: int64

In [49]:
df_2005[(df_2005['PARK_IT']=="Yes")].value_counts('ai_guess')

ai_guess
safety_equipment    43
others               6
chasies              4
Name: count, dtype: int64

In [55]:
df_2025[df_2025['COMPNAME']=="ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION BATTERY:MANAGEMENT SYSTEM/ENERGY CONTROL MODULE (BMS/BECM):SOFTWARE"].head(50)

,Unnamed: 0,RECORD_ID,CAMPNO,MAKETXT,MODELTXT,YEARTXT,MFGCAMPNO,COMPNAME,MFGNAME,BGMAN,ENDMAN,RCLTYPECD,POTAFF,ODATE,INFLUENCED_BY,MFGTXT,RCDATE,DATEA,RPNO,FMVSS,DESC_DEFECT,CONEQUENCE_DEFECT,CORRECTIVE_ACTION,NOTES,RCL_CMPT_ID,MFR_COMP_NAME,MFR_COMP_DESC,MFR_COMP_PTNO,PARK_IT,PARK_OUTSIDE,ai_guess
113,113,256356,24V475000,SEA ELECTRIC,5E,2025,NaN,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,SEA Electric LLC,NaN,NaN,V,174,20240724.0,MFR,SEA Electric LLC,20240624,20240626,NaN,NaN,SEA Electric LLC (SEA Electric) is recalling c...,A loss of drive power increases the risk of a ...,"Dealers will update the BMS software, free of ...",Owners may also contact the National Highway T...,127153005649095000001778,Software,Battery Management System Software,December 2022 iterations and earlier,No,No,software
200,200,261272,24V372000,MERCEDES-BENZ,EQE SUV 500 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647804000001778,SW BAT.MGMT,SW BAT.MGMT,A7899029204,No,No,software
201,201,261273,24V372000,MERCEDES-BENZ,EQE SUV 500 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647804000001778,SW BAT.MGMT,SW BAT.MGMT,A7899029104,No,No,software
202,202,261274,24V372000,MERCEDES-BENZ,EQE SUV 500 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647804000001778,SW BAT.MGMT,SW BAT.MGMT,A7899028804,No,No,software
203,203,261275,24V372000,MERCEDES-BENZ,EQE SUV 500 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647804000001778,SW BAT.MGMT,SW BAT.MGMT,A7899028704,No,No,software
205,205,261277,24V372000,MERCEDES-BENZ,EQE SUV 500 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647804000001778,SW BAT.MGMT,SW BAT.MGMT,A7899028604,No,No,software
206,206,261278,24V372000,MERCEDES-BENZ,EQE SUV 500 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647804000001778,SW BAT.MGMT,SW BAT.MGMT,A7899027104,No,No,software
207,207,261279,24V372000,MERCEDES-BENZ,EQE SUV 500 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647804000001778,SW BAT.MGMT,SW BAT.MGMT,A7899025505,No,No,software
208,208,261280,24V372000,MERCEDES-BENZ,EQE SUV 500 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647804000001778,SW BAT.MGMT,SW BAT.MGMT,A7899025405,No,No,software
209,209,261281,24V372000,MERCEDES-BENZ,EQE SUV 500 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647804000001778,SW BAT.MGMT,SW BAT.MGMT,A7899024805,No,No,software
211,211,261283,24V372000,MERCEDES-BENZ,EQE SUV 500 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647804000001778,SW BAT.MGMT,SW BAT.MGMT,A7899024705,No,No,software
212,212,261284,24V372000,MERCEDES-BENZ,EQE SUV 500 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647804000001778,SW BAT.MGMT,SW BAT.MGMT,A7899024605,No,No,software
213,213,261285,24V372000,MERCEDES-BENZ,EQE SUV 500 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647804000001778,SW BAT.MGMT,SW BAT.MGMT,A7899024005,No,No,software
214,214,261286,24V372000,MERCEDES-BENZ,EQE SUV 500 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647804000001778,SW BAT.MGMT,SW BAT.MGMT,A7899023905,No,No,software
215,215,261287,24V372000,MERCEDES-BENZ,EQE SUV 500 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647804000001778,SW BAT.MGMT,SW BAT.MGMT,A7899021705,No,No,software
222,222,261322,24V372000,MERCEDES-BENZ,EQS SUV 580 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647814000001778,SW BAT.MGMT,SW BAT.MGMT,A7899029204,No,No,software
223,223,261323,24V372000,MERCEDES-BENZ,EQS SUV 580 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647814000001778,SW BAT.MGMT,SW BAT.MGMT,A7899029104,No,No,software
225,225,261325,24V372000,MERCEDES-BENZ,EQS SUV 580 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647814000001778,SW BAT.MGMT,SW BAT.MGMT,A7899028804,No,No,software
226,226,261326,24V372000,MERCEDES-BENZ,EQS SUV 580 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647814000001778,SW BAT.MGMT,SW BAT.MGMT,A7899028704,No,No,software
227,227,261327,24V372000,MERCEDES-BENZ,EQS SUV 580 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647814000001778,SW BAT.MGMT,SW BAT.MGMT,A7899028604,No,No,software
228,228,261328,24V372000,MERCEDES-BENZ,EQS SUV 580 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647814000001778,SW BAT.MGMT,SW BAT.MGMT,A7899027104,No,No,software
229,229,261329,24V372000,MERCEDES-BENZ,EQS SUV 580 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647814000001778,SW BAT.MGMT,SW BAT.MGMT,A7899025505,No,No,software
231,231,261331,24V372000,MERCEDES-BENZ,EQS SUV 580 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647814000001778,SW BAT.MGMT,SW BAT.MGMT,A7899025405,No,No,software
232,232,261332,24V372000,MERCEDES-BENZ,EQS SUV 580 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647814000001778,SW BAT.MGMT,SW BAT.MGMT,A7899024805,No,No,software
233,233,261333,24V372000,MERCEDES-BENZ,EQS SUV 580 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647814000001778,SW BAT.MGMT,SW BAT.MGMT,A7899024705,No,No,software
234,234,261334,24V372000,MERCEDES-BENZ,EQS SUV 580 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647814000001778,SW BAT.MGMT,SW BAT.MGMT,A7899024605,No,No,software
235,235,261335,24V372000,MERCEDES-BENZ,EQS SUV 580 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647814000001778,SW BAT.MGMT,SW BAT.MGMT,A7899024005,No,No,software
237,237,261337,24V372000,MERCEDES-BENZ,EQS SUV 580 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647814000001778,SW BAT.MGMT,SW BAT.MGMT,A7899023905,No,No,software
238,238,261338,24V372000,MERCEDES-BENZ,EQS SUV 580 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647814000001778,SW BAT.MGMT,SW BAT.MGMT,A7899021705,No,No,software
240,240,261356,24V372000,MERCEDES-BENZ,EQS SUV 450 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647807000001778,SW BAT.MGMT,SW BAT.MGMT,A7899029204,No,No,software
241,241,261357,24V372000,MERCEDES-BENZ,EQS SUV 450 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647807000001778,SW BAT.MGMT,SW BAT.MGMT,A7899029104,No,No,software
242,242,261358,24V372000,MERCEDES-BENZ,EQS SUV 450 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647807000001778,SW BAT.MGMT,SW BAT.MGMT,A7899028804,No,No,software
243,243,261359,24V372000,MERCEDES-BENZ,EQS SUV 450 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647807000001778,SW BAT.MGMT,SW BAT.MGMT,A7899028704,No,No,software
244,244,261361,24V372000,MERCEDES-BENZ,EQS SUV 450 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647807000001778,SW BAT.MGMT,SW BAT.MGMT,A7899028604,No,No,software
245,245,261362,24V372000,MERCEDES-BENZ,EQS SUV 450 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647807000001778,SW BAT.MGMT,SW BAT.MGMT,A7899027104,No,No,software
246,246,261363,24V372000,MERCEDES-BENZ,EQS SUV 450 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647807000001778,SW BAT.MGMT,SW BAT.MGMT,A7899025505,No,No,software
247,247,261364,24V372000,MERCEDES-BENZ,EQS SUV 450 4MATIC,2025,2024060002,ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION B...,"Mercedes-Benz USA, LLC",20230201.0,20240511.0,V,14912,20240705.0,MFR,"Mercedes-Benz USA, LLC",20240528,20240528,NaN,NaN,"Mercedes-Benz USA, LLC (MBUSA) is recalling ce...",A sudden loss of drive power increases the ris...,Dealers will update the battery management sys...,Owners may also contact the National Highway T...,127033005647807000001778,SW BAT.MGMT,SW BAT.MGMT,A7899025405,No,No,software

In [74]:
subset_2025=df_2025.drop_duplicates(subset='CAMPNO')

In [194]:
subset_2025.sort_values('POTAFF',ascending=False).head(20)

,Unnamed: 0,RECORD_ID,CAMPNO,MAKETXT,MODELTXT,YEARTXT,MFGCAMPNO,COMPNAME,MFGNAME,BGMAN,ENDMAN,RCLTYPECD,POTAFF,ODATE,INFLUENCED_BY,MFGTXT,RCDATE,DATEA,RPNO,FMVSS,DESC_DEFECT,CONEQUENCE_DEFECT,CORRECTIVE_ACTION,NOTES,RCL_CMPT_ID,MFR_COMP_NAME,MFR_COMP_DESC,MFR_COMP_PTNO,PARK_IT,PARK_OUTSIDE,ai_guess
9283,9283,322045,26V104000,FORD,F-600 SD,2025,26C10,EXTERIOR LIGHTING:TAIL LIGHTS,Ford Motor Company,NaN,NaN,V,4381878,20260325.0,MFR,Ford Motor Company,20260220,20260223,NaN,108.0,Ford Motor Company (Ford) is recalling certain...,Trailer lights or brakes that do not function ...,The integrated trailer module software will be...,NaN,261027005672927000000223,Trailer Module (TRM),Integrated Trailer Module,High End: XXXX-19J294-B*,No,No,electronics
1562,1562,287576,24V744000,HONDA,CR-V,2025,"SJS, MJU, QJT, VJV",STEERING,Honda (American Honda Motor Co.),20210805.0,20240903.0,V,1693199,20241118.0,ODI,Honda (American Honda Motor Co.),20241003,20241004,NaN,NaN,Honda (American Honda Motor Co.) is recalling ...,Difficulty steering can increase the risk of a...,Dealers will replace the worm gear spring and ...,Owners may also contact the National Highway T...,127519005647927000000001,"GEAR BOX ASSY, STRG","GEAR BOX ASSY, STRG",53640-T60 -3050-M1,No,No,chasies
9447,9447,323039,26V363000,JEEP,GLADIATOR,2025,21D,STEERING:HYDRAULIC POWER ASSIST:PUMP,"Chrysler (FCA US, LLC)",NaN,20241202.0,V,1076999,NaN,ISSUE_INVGSTN,"Chrysler (FCA US, LLC)",20260604,20260604,NaN,NaN,"Chrysler (FCA US, LLC) is recalling certain 20...",A vehicle fire increases the risk of injury.,Owners are advised to park outside and away fr...,NaN,261347005643760000000012,Electric Hydraulic Power Steering Pump,Electric Hydraulic Power Steering Pump,"See attached file titled ""FCA US LLC Recall Pa...",No,Yes,powertrain
1979,1979,292219,25V315000,FORD,TRANSIT,2025,25S49,BACK OVER PREVENTION:SOFTWARE,Ford Motor Company,NaN,20250313.0,V,1076138,20251008.0,ODI,Ford Motor Company,20250509,20250512,NaN,NaN,Ford Motor Company (Ford) is recalling certain...,A frozen or missing rearview camera image can ...,The accessory protocol interface module (APIM)...,Owners may also contact the National Highway T...,128249005662419000001881,Accessory Protocol Interface Module (APIM),MOD.ASY.SCL.CONN.M/MEDIA,PU5T-14G682-*,No,No,software
8836,8836,319749,26V366000,HONDA,ACCORD HYBRID,2025,DOV,TIRES:TEMPORARY/EMERGENCY SPARE TIRE,Honda (American Honda Motor Co.),20221214.0,20260520.0,V,1049883,NaN,MFR,Honda (American Honda Motor Co.),20260604,20260605,NaN,NaN,Honda (American Honda Motor Co.) is recalling ...,A detached bottle cap can become a projectile ...,Dealers will replace the tire repair kit nozzl...,NaN,261350005664416000000307,Kit Assy Tire Repair,Kit Assy Tire Repair,42770-3D4-A01,No,No,others
2109,2109,293385,25V744000,TOYOTA,PRIUS,2025,25TB13/25LB06/WRE25,BACK OVER PREVENTION:DISPLAY FUNCTION,Toyota Motor Engineering & Manufacturing,20221012.0,20250701.0,V,1024407,20251205.0,MFR,Toyota Motor Corporation,20251030,20251030,NaN,111.0,Toyota Motor Engineering & Manufacturing (Toyo...,A rearview camera that fails to display an ima...,Dealers will update the parking assist softwar...,NaN,260709005636690000001883,"Computer, Parking Assist",Parking Assist ECU,86792-33180,No,No,software
9040,9040,320615,26V124000,FORD,BRONCO,2025,26S09,BACK OVER PREVENTION:SOFTWARE,Ford Motor Company,NaN,NaN,V,849310,20260413.0,MFR,Ford Motor Company,20260303,20260304,NaN,NaN,Ford Motor Company (Ford) is recalling certain...,A rearview camera that fails to display an ima...,"The APIM software will be updated by a dealer,...",NaN,261048005662299000001881,APIM (Accessory Protocol Interface Module),Sync 4 mid/high variant – 26MY Bronco,VU5T-14G670-XXX,No,No,electronics
1151,1151,282815,24V763000,HONDA,CIVIC HYBRID,2025,PJW,"FUEL SYSTEM, GASOLINE:DELIVERY:FUEL PUMP",Honda (American Honda Motor Co.),NaN,NaN,V,720810,20250220.0,MFR,Honda (American Honda Motor Co.),20241014,20241015,NaN,NaN,Honda (American Honda Motor Co.) is recalling ...,A fuel leak in the presence of an ignition sou...,Dealers will inspect and replace the high-pres...,Owners may also contact the National Highway T...,127556005660324000000152,"PUMP ASSY,FUEL H/P","PUMP ASSY,FUEL H/P",16790-6MA-J012-M1,No,No,powertrain
1035,1035,282135,24V935000,TESLA,MODEL 3,2025,SB-24-00-018,TIRES:PRESSURE MONITORING AND REGULATING SYSTEMS,"Tesla, Inc.",NaN,NaN,V,696281,20250215.0,MFR,"Tesla, Inc.",20241217,20241218,NaN,138.0,"Tesla, Inc. (Tesla) is recalling certain 2024 ...",Driving with improperly inflated tires increas...,Tesla released an over-the-air (OTA) software ...,Owners may also contact the National Highway T...,127753005662550000000308,Software Releases,"Software Release 2024.38.3, 2024.38.4, 2024.38...",NaN,No,No,electronics
2604,2604,294823,25V595000,TOYOTA,RAV4 PLUG-IN HYBRID,2025,See Part 573 Report,ELECTRICAL SYSTEM: INSTRUMENT CLUSTER/PANEL,Toyota Motor Engineering & Manufacturing,20220617.0,20240916.0,V,591377,20251205.0,ODI,Toyota Motor Corporation,20250911,20250912,NaN,NaN,Toyota Motor Engineering & Manufacturing (Toyo...,An instrument panel display that does not show...,Dealers will update the instrument panel softw...,NaN,260511005664495000001084,"Meter Assy, Combination",Combination Meter,83800-3AV30,No,No,software
4227,4227,301188,25V607000,HYUNDAI,PALISADE,2025,283,SEAT BELTS: REAR/OTHER:BUCKLE ASSEMBLY,Hyundai Motor America,NaN,20250616.0,V,568580,20260626.0,ODI,Hyundai Motor America,20250911,20250912,NaN,NaN,Hyundai Motor America (Hyundai) is recalling c...,Seat belt buckles that fail to latch may not p...,Passengers are advised to insert the belt firm...,NaN,260523005659265000001064,"1st, 2nd Row LH/RH Seatbelt Buckle",2nd Row RH Seatbelt Buckle,89840-S8000,No,No,safety_equipment
9279,9279,322007,26V034000,HYUNDAI,PALISADE,2025,292,AIR BAGS:SIDE/WINDOW:CURTAIN,Hyundai Motor America,NaN,20250616.0,V,568576,20260626.0,OVSC,Hyundai Motor America,20260122,20260123,NaN,226.0,Hyundai Motor America (Hyundai) is recalling c...,Improper side curtain air bag deployment incre...,Dealers will install a protective film over th...,NaN,260948005659265000001821,Module Curtain Airbag,Palisade LH specification,80410-S8500,No,No,safety_equipment
8984,8984,320349,26V059000,RAM,2500,2025,03D,ELECTRICAL SYSTEM: INTEGRATED TRAILER BRAKE CO...,"Chrysler (FCA US, LLC)",20240718.0,NaN,V,456287,20260317.0,MFR,"Chrysler (FCA US, LLC)",20260202,20260202,NaN,NaN,"Chrysler (FCA US, LLC) is recalling certain 20...",Trailer brake lights and turn signals that do ...,"Dealers will replace the trailer tow module, f...",NaN,260975005643767000001165,TRAILER BRAKE & TOWING CONTROL,TRAILER BRAKE & TOWING CONTROL,"68602158AE, 68602158AF, 68602158AG, 68602159AE...",No,No,electronics
4704,4704,303038,25V322000,TOYOTA,TUNDRA HYBRID,2025,25TB06 / 25TA06,EXTERIOR LIGHTING:BACK UP LIGHTS,Toyota Motor Engineering & Manufacturing,NaN,20250320.0,V,443444,20250911.0,MFR,Toyota Motor Corporation,20250515,20250519,NaN,NaN,Toyota Motor Engineering & Manufacturing (Toyo...,"Reverse light failure may reduce visibility, a...",Dealers will replace both reverse light assemb...,NaN,260205005636701000000225,"Lamp Assy, Rear, RH",Backup Lamp Assembly Including License Plate Lamp,81580-0C080,No,No,electronics
9401,9401,322732,26V316000,HYUNDAI,TUCSON PLUG-IN HYBRID,2025,302,FORWARD COLLISION AVOIDANCE: AUTOMATIC EMERGEN...,Hyundai Motor America,20250807.0,NaN,V,423062,20260622.0,ODI,Hyundai Motor America,20260518,20260519,NaN,NaN,Hyundai Motor America (Hyundai) is recalling c...,Unexpected braking increases the risk of a cra...,"Dealers will update the front camera software,...",NaN,261298005671793000001572,UNIT-FR VIEW CAMERA,Multi-function camera providing camera support...,99211-CW500,No,No,software
8610,8610,317327,26V328000,JEEP,GRAND CHEROKEE,2025,01D,AIR BAGS: AIR BAG/RESTRAINT CONTROL MODULE:SOF...,"Chrysler (FCA US, LLC)",NaN,NaN,V,419035,20260618.0,MFR,"Chrysler (FCA US, LLC)",20260521,20260521,NaN,214.0,"Chrysler (FCA US, LLC) is recalling certain 20...",Delayed air bag deployment during a crash incr...,Dealers will update the occupant restraint con...,NaN,261312005648744000001818,Occupant Restraint Controller,Occupant Restraint Controller,"Please see attached information titled ""FCA US...",No,No,software
4045,4045,300381,25V282000,VOLVO,EC40,2025,R10320,BACK OVER PREVENTION:SOFTWARE,"Volvo Car USA, LLC",NaN,NaN,V,413151,20250627.0,ODI,"Volvo Car USA, LLC",20250508,20250501,NaN,111.0,"Volvo Car USA, LLC (Volvo Car) is recalling ce...",A rearview camera image that does not display ...,The software will be updated by a dealer or th...,Owners may also contact the National Highway T...,128197005648771000001881,Wide Angle Vision Module (WAM) Software,Software,NaN,No,No,electronics
4384,4384,301751,25V908000,VOLVO,EC40,2025,R10333,BACK OVER PREVENTION:SOFTWARE,"Volvo Car USA, LLC",20240328.0,20240423.0,V,413151,20260302.0,ODI,"Volvo Car USA, LLC",20251223,20251229,NaN,111.0,"Volvo Car USA, LLC (Volvo Car) is recalling ce...",A rearview camera image that does not display ...,The software will be updated by a dealer or th...,NaN,260899005648771000001881,Software,Total Upgrade,NaN,No,No,electronics
3081,3081,296461,25V657000,TOYOTA,TUNDRA,2025,25TB10 / 25TA10,BACK OVER PREVENTION:SOFTWARE,Toyota Motor Engineering & Manufacturing,20211102.0,20250721.0,V,393838,20251119.0,MFR,Toyota Motor Corporation,20251001,20251002,NaN,111.0,Toyota Motor Engineering & Manufacturing (Toyo...,A rearview image that does not display reduces...,Dealers will update the multimedia display sof...,NaN,260613005636700000001881,"Receiver Assy, Radio & Navigation",Multimedia Display,86100-AN020,No,No,software
7428,7428,313249,25V900000,AUDI,E-TRON GT,2025,90TV,BACK OVER PREVENTION: SENSING SYSTEM: CAMERA,"Volkswagen Group of America, Inc.",NaN,NaN,V,356894,20260114.0,ODI,"Volkswagen Group of America, Inc.",20251219,20251222,NaN,111.0,"Volkswagen Group of America, Inc. (Audi) is re...",A rearview image that does not display reduces...,"Dealers will update the software, free of char...",NaN,260890005593439000001568,Software for the control unit of driver assist...,Software for the control unit of driver assist...,NaN,No,No,software

In [80]:
subset_2005=df_2005.drop_duplicates(subset='CAMPNO')

In [99]:
subset_2000=df_2000.drop_duplicates(subset='CAMPNO')

In [108]:
subset_2020=df_2020.drop_duplicates(subset='CAMPNO')

In [118]:
subset_2026=df_2026.drop_duplicates(subset='CAMPNO')

In [164]:
subset_2000=df_2000.drop_duplicates(subset='CAMPNO')
subset_2010=df_2010.drop_duplicates(subset='CAMPNO')
subset_2015=df_2015.drop_duplicates(subset='CAMPNO')

In [81]:
subset_2005.sort_values('POTAFF',ascending=False).head(10)

,Unnamed: 0,RECORD_ID,CAMPNO,MAKETXT,MODELTXT,YEARTXT,MFGCAMPNO,COMPNAME,MFGNAME,BGMAN,ENDMAN,RCLTYPECD,POTAFF,ODATE,INFLUENCED_BY,MFGTXT,RCDATE,DATEA,RPNO,FMVSS,DESC_DEFECT,CONEQUENCE_DEFECT,CORRECTIVE_ACTION,NOTES,RCL_CMPT_ID,MFR_COMP_NAME,MFR_COMP_DESC,MFR_COMP_PTNO,PARK_IT,PARK_OUTSIDE,ai_guess
837,837,114901,15V320000,HONDA,ACCORD,2005,JQ9 & JR0-JR8,AIR BAGS:FRONTAL:DRIVER SIDE:INFLATOR MODULE,Honda (American Honda Motor Co.),NaN,NaN,V,6281043,20150701.0,ODI,Honda (American Honda Motor Co.),20150528,20150528,NaN,NaN,Honda (American Honda Motor Co.) is recalling ...,In the event of a crash necessitating deployme...,"Honda will notify owners, and dealers will rep...",Owners may also contact the National Highway T...,57695000203660000000259,NaN,NaN,NaN,No,No,safety_equipment
664,664,103684,14V400000,CHEVROLET,IMPALA,2005,14350,ELECTRICAL SYSTEM:IGNITION,General Motors LLC,NaN,NaN,V,5877718,20140908.0,MFR,"General Motors, LLC",20140703,20140707,NaN,NaN,This defect can affect the safe operation of t...,"If the key is not in the run position, the air...","GM will notify owners, and dealers will instal...",Owners may also contact the National Highway T...,56617000204358000000212,NaN,NaN,NaN,No,No,others
890,890,118571,16V352000,DODGE,MAGNUM,2005,S43,AIR BAGS:FRONTAL:PASSENGER SIDE:INFLATOR MODULE,Chrysler (FCA US LLC),20040101.0,NaN,V,4648270,20170327.0,ODI,"Chrysler (FCA US, LLC)",20160524,20160524,NaN,NaN,Chrysler (FCA US LLC) expanded the affected po...,These vehicles are equipped with certain air b...,Owners are advised not to drive their vehicle ...,Owners may also contact the National Highway T...,58941000203493000001463,NaN,NaN,NaN,Yes,No,others
4497,4497,78604,09V388000,TOYOTA,TACOMA,2005,90L(TOYOTA)/90LG(LEX,VEHICLE SPEED CONTROL:ACCELERATOR PEDAL,"TOYOTA MOTOR NORTH AMERICA, INC.",NaN,NaN,V,4445056,20091231.0,MFR,Toyota Motor Corporation,20091005,20091006,NaN,NaN,TOYOTA IS RECALLING CERTAIN MODEL YEAR 2004-20...,A STUCK OPEN ACCELERATOR PEDAL MAY RESULT IN V...,TOYOTA FILED AN AMENDED DEFECT REPORT ON NOVEM...,TOYOTA RECALL NO. 90L/90LG.OWNERS MAY ALSO CON...,33638000216309000000295,NaN,NaN,NaN,No,No,others
753,753,110224,15V313000,DODGE,DURANGO,2005,R25,AIR BAGS:FRONTAL:DRIVER SIDE:INFLATOR MODULE,Chrysler (FCA US LLC),NaN,NaN,V,4077169,20150608.0,ODI,"Chrysler (FCA US, LLC)",20150526,20150527,NaN,NaN,Chrysler (FCA US LLC) is recalling certain mod...,In the event of a crash necessitating deployme...,Owners are advised not to drive their vehicle ...,Owners may also contact the National Highway T...,57688000201366000000259,NaN,NaN,NaN,Yes,No,safety_equipment
846,846,115009,15V370000,HONDA,ACCORD,2005,"JU4, JU5, JU6, JU7",AIR BAGS:FRONTAL:PASSENGER SIDE:INFLATOR MODULE,Honda (American Honda Motor Co.),20040618.0,20050330.0,V,3498481,20150701.0,ODI,Honda (American Honda Motor Co.),20150615,20150615,NaN,NaN,Honda (American Honda Motor Co.) is recalling ...,In the event of a crash necessitating deployme...,"Honda will notify owners, and dealers will rep...",Owners may also contact the National Highway T...,57752000203660000001463,NaN,NaN,NaN,No,No,safety_equipment
713,713,106865,14V355000,CADILLAC,DEVILLE,2005,14299,ELECTRICAL SYSTEM:IGNITION,General Motors LLC,20040318.0,20050624.0,V,3141731,20140923.0,MFR,"General Motors, LLC",20140623,20140623,NaN,NaN,This defect can affect the safe operation of t...,"If the key is not in the run position, the air...","GM will notify owners, and dealers will instal...",Owners may also contact the National Highway T...,56552000204366000000212,NaN,NaN,NaN,No,No,electronics
641,641,102734,14V252000,CHEVROLET,MALIBU,2005,13036,ELECTRONIC STABILITY CONTROL (ESC),General Motors LLC,20040330.0,20050729.0,V,2440524,20140818.0,ODI,"General Motors, LLC",20140514,20140515,NaN,NaN,General Motors LLC (GM) is recalling certain m...,Any of the above failure conditions increases ...,"GM will notify owners, and dealers will attach...",Owners may also contact the National Highway T...,56435000204359000001145,NaN,NaN,NaN,No,No,electronics
865,865,116118,16V061000,ACURA,RL,2005,"JY0, JY1, JY2",AIR BAGS:FRONTAL:DRIVER SIDE:INFLATOR MODULE,Honda (American Honda Motor Co.),20040223.0,20050623.0,V,2232187,20170222.0,ODI,Honda (American Honda Motor Co.),20160203,20160203,NaN,NaN,Honda (American Honda Motor Co.) is recalling ...,In the event of a crash necessitating deployme...,"Honda will notify owners, and dealers will rep...",Owners may also contact the National Highway T...,58503000203819000000259,NaN,NaN,NaN,No,No,safety_equipment
251,251,86998,10V017000,TOYOTA,AVALON,2005,AOA,VEHICLE SPEED CONTROL:ACCELERATOR PEDAL,"TOYOTA MOTOR NORTH AMERICA, INC.",20040917.0,20100118.0,V,2230661,20100205.0,MFR,Toyota Motor Corporation,20100121,20100121,NaN,NaN,TOYOTA IS RECALLING CERTAIN MODEL YEAR 2005-20...,THE ACCELERATOR PEDAL MAY BECOME HARD TO DEPRE...,DEALERS WILL INSTALL A REINFORCEMENT BAR IN TH...,TOYOTA SAFETY RECALL NO. AOA. OWNERS MAY ALSO ...,34837000216205000000295,NaN,NaN,NaN,No,No,powertrain

In [91]:
df_2025.groupby('ai_guess')['POTAFF'].mean().sort_values(ascending=False)

ai_guess
software            706329.070996
electronics         314522.375736
chasies             116997.104072
powertrain          103090.149457
others               52277.153125
safety_equipment     37011.782051
Name: POTAFF, dtype: float64

In [102]:
df_2025.value_counts('ai_guess')

ai_guess
software            4620
electronics         1698
others              1280
chasies             1105
safety_equipment     546
powertrain           368
Name: count, dtype: int64

In [110]:
df_2020.value_counts('ai_guess')

ai_guess
software            10657
others               3521
electronics          2952
safety_equipment     2308
powertrain           2097
chasies              1563
Name: count, dtype: int64

In [117]:
df_2026.value_counts('ai_guess')

ai_guess
software            1046
electronics          763
others               545
safety_equipment     403
chasies              376
powertrain           122
Name: count, dtype: int64

In [93]:
subset_2025.value_counts('ai_guess')

ai_guess
others              317
electronics         211
chasies             166
safety_equipment    128
software            102
powertrain           88
Name: count, dtype: int64

In [101]:
subset_2000.value_counts('ai_guess')

ai_guess
others              518
chasies             341
electronics         230
safety_equipment    174
powertrain          122
software             11
Name: count, dtype: int64

In [111]:
subset_2020.value_counts('ai_guess')

ai_guess
others              564
electronics         425
chasies             363
safety_equipment    293
powertrain          285
software            133
Name: count, dtype: int64

In [119]:
subset_2026.value_counts('ai_guess')

ai_guess
others              147
electronics         108
safety_equipment     77
chasies              62
powertrain           42
software             39
Name: count, dtype: int64

In [94]:
subset_2025.groupby('ai_guess')['POTAFF'].sum().sort_values(ascending=False)

ai_guess
electronics         13759662
software             7500707
others               5165490
safety_equipment     3112147
powertrain           3047020
chasies              3020686
Name: POTAFF, dtype: int64

In [100]:
subset_2000.groupby('ai_guess')['POTAFF'].sum().sort_values(ascending=False)

ai_guess
others              30678810
electronics         30526819
chasies             16069923
powertrain          11594459
safety_equipment     8173222
software              550898
Name: POTAFF, dtype: int64

In [109]:
subset_2020.groupby('ai_guess')['POTAFF'].sum().sort_values(ascending=False)

ai_guess
electronics         23819110
others              17846132
powertrain          14407661
software            12757145
safety_equipment    12177789
chasies              4440342
Name: POTAFF, dtype: int64

In [115]:
data_dir=''
df_2020.to_csv(data_dir + 'Recall_classified2020.csv')

In [128]:
count_model_2000=df_2000.value_counts('ai_guess').reset_index()
count_model_2005=df_2005.value_counts('ai_guess').reset_index()
count_model_2010=df_2010.value_counts('ai_guess').reset_index()
count_model_2015=df_2015.value_counts('ai_guess').reset_index()
count_model_2020=df_2020.value_counts('ai_guess').reset_index()
count_model_2025=df_2025.value_counts('ai_guess').reset_index()

In [133]:
count_model=pd.merge(count_model_2000, count_model_2005, on='ai_guess')

In [134]:
count_model=pd.merge(count_model, count_model_2010, on='ai_guess')

In [154]:
count_model_2000=count_model_2000.rename(columns={'count': '2000'})
count_model_2005=count_model_2005.rename(columns={'count': '2005'})
count_model_2010=count_model_2010.rename(columns={'count': '2010'})
count_model_2015=count_model_2015.rename(columns={'count': '2015'})
count_model_2020=count_model_2020.rename(columns={'count': '2020'})
count_model_2025=count_model_2025.rename(columns={'count': '2025'})

In [155]:
count_model_2025

           ai_guess  2025
0          software  4620
1       electronics  1698
2            others  1280
3           chasies  1105
4  safety_equipment   546
5        powertrain   368

In [169]:
count_model=pd.merge(count_model_2000, count_model_2005, on='ai_guess')
count_model=pd.merge(count_model, count_model_2010, on='ai_guess')
count_model=pd.merge(count_model, count_model_2015, on='ai_guess')
count_model=pd.merge(count_model, count_model_2020, on='ai_guess')
count_model=pd.merge(count_model, count_model_2025, on='ai_guess')
count_model=count_model.rename(columns={'ai_guess': 'group'})

In [170]:
count_model

              group  2000  2005  2010  2015   2020  2025
0            others  1390  1694  1926  2212   3521  1280
1           chasies   773   766   687  1193   1563  1105
2       electronics   674   652  1098  1196   2952  1698
3  safety_equipment   513  1074  2009  1437   2308   546
4        powertrain   284   421   607   908   2097   368
5          software    32    66   260   445  10657  4620

In [166]:
count_camp_2000=subset_2000.value_counts('ai_guess').reset_index()
count_camp_2005=subset_2005.value_counts('ai_guess').reset_index()
count_camp_2010=subset_2010.value_counts('ai_guess').reset_index()
count_camp_2015=subset_2015.value_counts('ai_guess').reset_index()
count_camp_2020=subset_2020.value_counts('ai_guess').reset_index()
count_camp_2025=subset_2025.value_counts('ai_guess').reset_index()
count_camp_2000=count_camp_2000.rename(columns={'count': '2000'})
count_camp_2005=count_camp_2005.rename(columns={'count': '2005'})
count_camp_2010=count_camp_2010.rename(columns={'count': '2010'})
count_camp_2015=count_camp_2015.rename(columns={'count': '2015'})
count_camp_2020=count_camp_2020.rename(columns={'count': '2020'})
count_camp_2025=count_camp_2025.rename(columns={'count': '2025'})
count_camp=pd.merge(count_camp_2000, count_camp_2005, on='ai_guess')
count_camp=pd.merge(count_camp, count_camp_2010, on='ai_guess')
count_camp=pd.merge(count_camp, count_camp_2015, on='ai_guess')
count_camp=pd.merge(count_camp, count_camp_2020, on='ai_guess')
count_camp=pd.merge(count_camp, count_camp_2025, on='ai_guess')

In [175]:
count_model=count_model.transpose()

In [190]:
count_model.index.name = "group"
count_model.to_csv('count_model.csv', index=True)

In [178]:
count_model.reset_index()

   index       0        1            2                 3           4         5
0  group  others  chasies  electronics  safety_equipment  powertrain  software
1   2000    1390      773          674               513         284        32
2   2005    1694      766          652              1074         421        66
3   2010    1926      687         1098              2009         607       260
4   2015    2212     1193         1196              1437         908       445
5   2020    3521     1563         2952              2308        2097     10657
6   2025    1280     1105         1698               546         368      4620

In [179]:
count_model.columns = count_model.iloc[0]

In [192]:
count_model

group others chasies electronics safety_equipment powertrain software    sum
group
2000    1390     773         674              513        284       32   3666
2005    1694     766         652             1074        421       66   4673
2010    1926     687        1098             2009        607      260   6587
2015    2212    1193        1196             1437        908      445   7391
2020    3521    1563        2952             2308       2097    10657  23098
2025    1280    1105        1698              546        368     4620   9617

In [182]:
count_model=count_model.drop(index='group')

In [191]:
count_model["sum"] = count_model[
    ["others", "chasies", "electronics", "safety_equipment", "powertrain", "software"]
].sum(axis=1)